housingredirect/urls.py
from django.urls import path
from . import views

app_name = 'housingredirect'

urlpatterns = [
    path('', views.about, name='about'),
    path('form/', views.index, name='form'),
]

zipfinder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('housingredirect.urls')),
]

housingredirect/models.py
from django.db import models

# Create your models here.

class ZipRelation(models.Model):
    zip = models.IntegerField()
    targetID = models.IntegerField()
    distance = models.FloatField()
    one_bed_rent = models.FloatField()
    two_bed_rent = models.FloatField()
    three_bed_rent = models.FloatField()
    four_bed_rent = models.FloatField()
    tot_20_24 = models.IntegerField()
    pct_20_24 = models.FloatField()
    pct_male_20_24 = models.FloatField()
    pct_female_20_24 = models.FloatField()
    tot_25_29 = models.IntegerField()
    pct_25_29 = models.FloatField()
    pct_male_25_29 = models.FloatField()
    pct_female_25_29 = models.FloatField()
    tot_male_20_34 = models.IntegerField()
    nev_mar_male_20_34 = models.FloatField()
    tot_male_35_44 = models.IntegerField()
    nev_mar_male_35_44 = models.FloatField()
    tot_female_20_34 = models.IntegerField()
    nev_mar_female_20_34 = models.FloatField()
    tot_female_35_44 = models.IntegerField()
    nev_mar_female_35_44 = models.FloatField()
    tot_drive = models.FloatField()
    tot_drive_alone = models.FloatField()
    tot_drive_carpool = models.FloatField()
    tot_pub = models.FloatField()
    tot_walk = models.FloatField()
    tot_bike = models.FloatField()
    pct_span = models.FloatField()
    pct_euro = models.FloatField()
    pct_asia = models.FloatField()
    travel_time = models.FloatField()
    unmarried_20_34 = models.FloatField()
    unmarried_35_44 = models.FloatField()

housingredirect/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator


class ZipFinderForm(forms.Form):
    work_zip = forms.IntegerField(label='Work ZIP Code')
    age = forms.IntegerField(label='Age')
    gender = forms.ChoiceField(label='Preferred Gender for Roommates', choices=[('Male', 'Male'), ('Female', 'Female'), ('No Preference', 'No Preference')])
    gender_prio = forms.ChoiceField(label='Priority of Gender Selection (4 highest, 1 lowest)', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    bedrooms = forms.ChoiceField(label='Number of Bedrooms', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    transportation = forms.ChoiceField(label='Preferred Method of Transportation', choices=[('Driving Alone','Driving Alone'),
                                                                                            ('Carpooling', 'Carpooling'),
                                                                                            ('Public Transit','Public Transit'),
                                                                                            ('Biking', 'Biking'),
                                                                                            ('Walking', 'Walking')])
    trans_prio = forms.ChoiceField(label='Transportation Method Priority (4 highest, 1 lowest)', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    pets = forms.ChoiceField(label='Do you have a pet?', choices=[('Yes', 'Yes'), ('No', 'No')])
    min_rent = forms.ChoiceField(label='Minimum Total Monthly Rent', choices=[(0, 0), (500, 500), (750, 750), (1000, 1000),
                                                                 (1250, 1250), (1500, 1500), (1750, 1750), (2000, 2000),
                                                                 (2250, 2250), (2500, 2500), (2750, 2750), (3000, 3000)])
    max_rent = forms.ChoiceField(label='Maximum Total Monthly Rent', choices=[(0, 0), (500, 500), (750, 750), (1000, 1000),
                                                                 (1250, 1250), (1500, 1500), (1750, 1750), (2000, 2000),
                                                                 (2250, 2250), (2500, 2500), (2750, 2750),
                                                                 (3000, 3000), (9999, 'Any Price')])
    relationship = forms.ChoiceField(label='Are you looking for a relationship? If so, what gender?', choices=[('Male', 'Yes, male'),
                                                                                                               ('Female', 'Yes, female'),
                                                                                                               ('Either', 'Yes, either'),
                                                                                                                ('No', 'No')])
    rel_prio = forms.ChoiceField(label='Relationship Priority (4 highest, 1 lowest)', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])
    language = forms.ChoiceField(label='Do you prefer to live around people who speak languages other than English? If so, which?',
                                 choices=[('Spanish', 'Yes, Spanish'), ('European', 'Yes, other European languages'), ('Asian', 'Yes, Asian languages'),
                                          ('No', 'No')])
    lang_prio = forms.ChoiceField(label='Language Priority (4 highest, 1 lowest)', choices=[(1, 1), (2, 2), (3, 3), (4, 4)])

housingredirect/views.py
from django.shortcuts import render
from .forms import ZipFinderForm
from .models import ZipRelation
from django.http import HttpResponseRedirect


def index(request):
    if request.method == 'POST':
        form = ZipFinderForm(request.POST)
        if form.is_valid():
            cleaned_form = form.cleaned_data
            age = cleaned_form['age']
            gender = cleaned_form['gender']
            trans = cleaned_form['transportation']
            beds = cleaned_form['bedrooms']
            gender_prio = int(cleaned_form['gender_prio'])
            trans_prio = int(cleaned_form['trans_prio'])
            min_rent = int(cleaned_form['min_rent'])
            max_rent = int(cleaned_form['max_rent'])
            relationship = cleaned_form['relationship']
            language = cleaned_form['language']
            rel_prio = int(cleaned_form['rel_prio'])
            lang_prio = int(cleaned_form['lang_prio'])
            pets = 1 if cleaned_form['pets'] == 'Yes' else 0
            if age < 20:
                return render(request, 'error.html', {'errormessage': 'This tool can only provide recommendations for people between 20 and 29 years of age'})
            if max_rent < min_rent:
                return render(request, 'error.html', {'errormessage': 'Your max rent value was less than your min'})
            if age > 29:
                return HttpResponseRedirect('https://www.aarp.org/')
            if trans == 'Walk':
                zips = ZipRelation.objects.filter(targetID=cleaned_form['work_zip'], distance__lte=2500)
            elif trans == 'Bike':
                zips = ZipRelation.objects.filter(targetID=cleaned_form['work_zip'], distance__lte=8000)
            else:
                zips = ZipRelation.objects.filter(targetID=cleaned_form['work_zip'])
            if zips:
                pass
            else:
                zips = ZipRelation.objects.filter(targetID=cleaned_form['work_zip'])
            max_utility = float('-inf')
            try:
                best_zip = zips[0]
            except:
                return render(request, 'error.html', {'errormessage': 'The zip code you entered was invalid or not in our database, please try another zip code'})
            if cleaned_form['work_zip'] < 1000 or cleaned_form['work_zip'] > 99999:
                return render(request, 'error.html', {'errormessage': 'The zip code you entered was invalid or not in our database, please try another zip code'})
            if zips:
                pass
            else:
                return render(request, 'error.html', {'errormessage': 'The zip code you entered was not in our database, please try another zip code'})
            for zr in zips:
                distanceval = zr.distance
                if gender == 'Male':
                    genderval = zr.pct_male_20_24 if 20 <= age <= 24 else zr.pct_male_25_29
                elif gender == 'Female':
                    genderval = zr.pct_female_20_24 if 20 <= age <= 24 else zr.pct_female_25_29
                else:
                    genderval = (zr.pct_male_20_24 + zr.pct_female_20_24) / 2 if 20 <= age <= 24 else (zr.pct_male_25_29 + zr.pct_female_25_29) / 2
                if trans == 'Drive Alone':
                    transval = zr.tot_drive_alone
                elif trans == 'Carpool':
                    transval = zr.tot_carpool
                elif trans == 'Public Transit':
                    transval = zr.tot_pub
                elif trans == 'Walk':
                    transval = zr.tot_walk
                else:
                    transval = zr.tot_bike
                if beds == 1:
                    rentval = zr.one_bed_rent
                elif beds == 2:
                    rentval = zr.two_bed_rent / 2
                elif beds == 3:
                    rentval = zr.three_bed_rent / 3
                else:
                    rentval = zr.four_bed_rent / 4
                if relationship == 'Male':
                    relval = zr.nev_mar_male_20_34
                elif relationship == 'Female':
                    relval = zr.nev_mar_female_20_34
                elif relationship == 'Either':
                    relval = (zr.nev_mar_female_20_34 + zr.nev_mar_male_20_34) / 2
                else:
                    relval = 0
                if language == 'Spanish':
                    langval = zr.pct_span
                elif language == 'European':
                    langval = zr.pct_euro
                elif language == 'Asian':
                    langval = zr.pct_asia
                else:
                    langval = 0
                utility = genderval * gender_prio + transval * trans_prio + relval * rel_prio + langval * lang_prio - rentval - distanceval
                best_zip = zr if utility > max_utility else best_zip
                max_utility = utility if utility > max_utility else max_utility
            if max_rent > 3000:
                return HttpResponseRedirect('https://www.zillow.com/homes/for_rent/{}/paymenta_sort/{}-_beds/{}_pets'.format(best_zip.zip, beds, pets))
            return HttpResponseRedirect('https://www.zillow.com/homes/for_rent/{}/{}-{}_mp/paymenta_sort/{}-_beds/{}_pets'.format(best_zip.zip, min_rent, max_rent, beds, pets))
    else:
        form = ZipFinderForm()
    return render(request, 'index.html', {'form': form})


def about(request):
    return render(request, 'about.html')

housingredirect/templates/about.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% load static %}
{% block content %}
<style>
    p {
          padding-right: 50px;
          padding-left: 25px;
          text-indent: 2.0em;
    }

    h1 {
        padding-top: 10px;
        padding-left: 15px;
    }

    a {
        padding-left: 10px;
        padding-bottom: 10px;
    }

    h2 {
        padding-left: 10px;
    }

    h6 {
        padding-left: 20px;
    }

</style>
<h1>About this Site</h1>
<h6>By: David Bennett, Ian Hardman, Julia Heinzel, and Andrew Vaaler</h6>
<p class="text-left">The goal of this site is to help young professionals find the ideal place to live based on their work location and a number of personal preferences. We utilize Zillow rental price data, GIS methods, and basic utility maximization to provide affordable housing options that meet the needs of all sorts of young workers. Below you will find a behind the scenes look at the data and methods that make this site function. We also address limitations of our product.
</p>
<p class="text-left">
We use Zillow’s ZIP Code level datasets for median rental prices of 1-, 2-, 3- and 4-bedroom apartments. Using these datasets allows us to give users the option of choosing the number of roommates they will have (i.e. 3 roommates for a 4-bedroom apartment). The Zillow data is, however, limited to only 95 ZIP Codes that occur in each of these datasets. We further limit the options to 78 ZIP Codes that are in major U.S. cities including Atlanta, Boston, Charlotte, Chicago, Dallas, Houston, Las Vegas, Los Angeles, Miami, New York, and Orlando. We refer to these as “home” ZIP Codes.
</p>
<p class="text-left">
Using the 2010 U.S. Census ZIP Code tabulation area shapefile from the Census Bureau’s TIGER/Line data portal, we calculate the distance between roughly 33,000 U.S. ZIP Codes and their nearest 400 neighbors. Combining this distance matrix with our set of Zillow ZIP Codes results in 31,200 possible work-home ZIP Code combinations (i.e. each of the 78 home ZIP Codes has 400 neighbors). While this is not ideal for a fully functioning site, it is more than enough for our proof of concept. In the image below you can see the ZIP Code where the University of Chicago is located as well as the six ZIP Codes in our dataset that are within its 400 nearest neighbors. So, while other nearby ZIP Codes may have better characteristics, we can only maximize utility between the six highlighted.
</p>
<img src="{% static 'mappic.png' %}" width="500px" style="padding-left: 20px">
<p class="text-left">
We match all of the “home” ZIP Codes to data from the American Community Survey. These data include proportion of population by gender and age group, proportion of population that walk, bike, drive, or take public transportation to work, and the average travel time for commuters. ACS also includes data on the proportion of population that speaks Spanish, Indo-European, or Asian and Pacific islander languages.
</p>
<p class="text-left">Finally, this tool is only meant for people ages 20-29, and entering an age outside that range will yield a <i>different</i> recommendation</p>
<p class="text-left">

    <ul> Some good ZIP codes to try out are:
        <li>60637 U of Chicago</li>
        <li>02143 Whole Foods Cambridge Massachusetts</li>
        <li>30313 Atlanta Aquarium</li>
    </ul>
</p>
<h2>Directions for Use</h2>
<ol>
    <li>Enter the zip code of the location where you will be working</li>
    <li>Enter your age</li>
    <li>Enter the preferred gender for your roommates</li>
    <li>Select a level of priority of how important the gender of your roommates is to you (4 being the most important and 1 being the least important)</li>
    <li>Enter the number of bedrooms you wish for your apartment to have</li>
    <li>Select the method of transportation you will utilize in your area*</li>
    <li>Select a level of priority of how important the method of transportation you utilize is to you (4 being the most important and 1 being the least important)</li>
    <li>Select whether or not you will have pets</li>
    <li>Enter the minimum you wish to pay for rent each month in total over your number of roommates (to the nearest $250)</li>
    <li>Enter the maximum you wish to pay for rent each month in total over your number of roommates (to the nearest $250)</li>
    <li>Enter whether or not you are currently looking for a relationship and if so, which gender?</li>
    <li>Select a level of priority of how important the prospect of a relationship is to you (4 being the most important and 1 being the least important)</li>
    <li>Enter whether or not you prefer to live with people that speak a language other than English, as well as the language you prefer</li>
    <li>Select a level of priority of how important it is to you that the people in your area speak a language other than English (4 being the most important and 1 being the least important)</li>
    <li>Press submit to receive your most compatible apartment listings</li>
</ol>
<a href="{% url 'housingredirect:form' %}">Click Here to Use the Tool</a>
<p>*- It is assumed that if you select walking as your method of transportation, the limit of how far this will be from your office will be 1.5 miles (or closest zip code) and if you select biking as your method of transportation, the limit will be 5 miles (or closest zip code)</p>
{% endblock %}

housingredirect/templates/error.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% block content %}
<h1>ERROR</h1>
{{ errormessage }}
<br>
<a href="{% url 'housingredirect:form' %}">Try Again?</a>


{% endblock %}

housingredirect/templates/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% block content %}

<div>Fill out the form below to receive a zip code recommendation</div>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <br>
    {{ field.label_tag }} {{ field }}
    <br>
    {% endfor %}
    <button type="submit">SUBMIT</button>
</form>

{% endblock %}